window.lang = {
    "en-us": {
        "title0": "Homepage",
        "title1": "Project",
        "title2": "Class album",
        "title3": "Blogs",
        "text0": "Nothing here!",
        "text1": "Other project",
        "text2": "Class album",
        "text3": "Name: ",
        "text4": "Birthday: ",
        "text5": "Wechat: ",
        "text6": "QQ: ",
        "text7": "E-mail: ",
        "text8": "Favourite food: ",
        "text9": "Favourite music: ",
        "text10": "Favourite movie: ",
        "text11": "Dedication: ",
        "text12": "Submit",
        "text13": "Blogs",
        "text14": " Gender: ",
        "text15": "Male",
        "text16": "Female",
        "text17": "Telephone: ",
        "text18": "Favourite food: ",
    },
    "zh-cn": {
        "title0": "起始页",
        "title1": "项目",
        "title2": "同学录",
        "title3": "博客",
        "text0": "这里什么也木有!",
        "text1": "其他项目",
        "text2": "同学录",
        "text3": "姓名: ",
        "text4": "生日: ",
        "text5": "微信: ",
        "text6": "QQ: ",
        "text7": "邮箱: ",
        "text8": "最喜欢的食物: ",
        "text9": "最喜欢的音乐: ",
        "text10": "最喜欢的电影: ",
        "text11": "留言: ",
        "text12": "提交",
        "text13": "博客",
        "text14": " 性别: ",
        "text15": "男",
        "text16": "女",
        "text17": "电话: ",
        "text18": "最喜欢的颜色: "
    }
}
